services:
  nginx:
    image: nginx:1.25-alpine
    container_name: ftm_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htdocs:/var/www/html:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - app_network
    restart: unless-stopped

  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ftm_php_fpm
    volumes:
      - ./htdocs:/var/www/html
    environment:
      - PHP_USER=1000
      - PHP_GROUP=1000
    networks:
      - app_network
    restart: unless-stopped

  mariadb:
    image: mariadb:11.2
    container_name: ftm_mariadb
    restart: unless-stopped
    ports:
      - "4306:3306"  # <== Expose MariaDB on port 3307 on the host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mariadb", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: ftm_redis_cache
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - app_network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: ftm_redisinsight
    ports:
      - "8001:5540"  # Maps host 8001 to container 5540
    volumes:
      - redisinsight_data:/data
    networks:
      - app_network
    restart: unless-stopped



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ftm_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: 3306  # <== Notice: INSIDE the Docker network, MariaDB still listens on 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app_network

volumes:
  mariadb_data:
  redis_data:
  nginx_logs:
  composer_cache:
  redisinsight_data:

networks:
  app_network:
    driver: bridge
